/**
 * Defines the colors scheme.
 * 
 * @returns `Object` with colors scheme.
 */
const colors = () => {
	return {
		"semanticHighlighting": false,
		"colors": {
			"foreground": { "array": 1, "position": 1 },
			"focusBorder": { "array": 1, "position": 1, "alpha": 0 },
			"selection.background": { "array": 1, "position": 1, "alpha": 0.35 },
			"scrollbar.shadow": { "array": 1, "position": 1, "alpha": 0 },
			"activityBar.foreground": { "array": 0, "position": 0 },
			"activityBar.background": { "array": 1, "position": 0 },
			"activityBar.inactiveForeground": { "array": 0, "position": 0, "alpha": 0.38 },
			"activityBarBadge.foreground": { "array": 1, "position": 1 },
			"activityBarBadge.background": { "array": 0, "position": 0 },
			"activityBar.border": { "array": 1, "position": 1, "alpha": 0 },
			"activityBar.activeBackground": { "array": 1, "position": 1, "alpha": 0 },
			"sideBar.background": { "array": 1, "position": 0 },
			"sideBar.foreground": { "array": 1, "position": 3 },
			"sideBarSectionHeader.background": { "array": 1, "position": 1, "alpha": 0 },
			"sideBarSectionHeader.foreground": { "array": 0, "position": 0 },
			"sideBarSectionHeader.border": { "array": 1, "position": 1, "alpha": 0 },
			"sideBarTitle.foreground": { "array": 1, "position": 1 },
			"sideBar.border": { "array": 1, "position": 1, "alpha": 0.05 },
			"list.inactiveSelectionBackground": { "array": 0, "position": 0, "alpha": 0.14 },
			"list.inactiveSelectionForeground": { "array": 0, "position": 5 },
			"list.hoverBackground": { "array": 1, "position": 1, "alpha": 0.03 },
			"list.hoverForeground": { "array": 1, "position": 3 },
			"list.activeSelectionBackground": { "array": 0, "position": 0, "alpha": 0.21 },
			"list.activeSelectionForeground": { "array": 1, "position": 1 },
			"tree.indentGuidesStroke": { "array": 1, "position": 1, "alpha": 0.1 },
			"tree.inactiveIndentGuidesStroke": { "array": 1, "position": 1, "alpha": 0 },
			"list.dropBackground": { "array": 1, "position": 2, "alpha": 0.09 },
			"list.highlightForeground": { "array": 0, "position": 0 },
			"list.focusBackground": { "array": 0, "position": 0, "alpha": 0.22 },
			"list.focusForeground": { "array": 1, "position": 1 },
			"listFilterWidget.background": { "array": 0, "position": 0 },
			"listFilterWidget.outline": { "array": 1, "position": 1, "alpha": 0 },
			"listFilterWidget.noMatchesOutline": "#be1100",
			"statusBar.foreground": { "array": 1, "position": 1 },
			"statusBar.background": { "array": 0, "position": 0 },
			"statusBarItem.hoverBackground": { "array": 1, "position": 0, "alpha": 0.15 },
			"statusBar.debuggingBackground": { "array": 1, "position": 1 },
			"statusBar.debuggingForeground": { "array": 1, "position": 0 },
			"statusBar.noFolderBackground": { "array": 1, "position": 0 },
			"statusBar.noFolderForeground": { "array": 1, "position": 1 },
			"statusBarItem.remoteBackground": { "array": 1, "position": 0 },
			"statusBarItem.remoteForeground": { "array": 1, "position": 1 },
			"titleBar.activeBackground": { "array": 1, "position": 0 },
			"titleBar.activeForeground": { "array": 1, "position": 2 },
			"titleBar.inactiveBackground": { "array": 1, "position": 0 },
			"titleBar.inactiveForeground": { "array": 1, "position": 7 },
			"titleBar.border": { "array": 1, "position": 1, "alpha": 0 },
			"menubar.selectionForeground": { "array": 0, "position": 0 },
			"menubar.selectionBackground": { "array": 1, "position": 0 },
			"menu.foreground": { "array": 1, "position": 2 },
			"menu.background": { "array": 1, "position": 0 },
			"menu.selectionForeground": { "array": 1, "position": 1 },
			"menu.selectionBackground": { "array": 0, "position": 0 },
			"menu.selectionBorder": { "array": 1, "position": 1, "alpha": 0 },
			"menu.separatorBackground": { "array": 1, "position": 1, "alpha": 0 },
			"menu.border": { "array": 1, "position": 1, "alpha": 0 },
			"button.background": { "array": 0, "position": 0 },
			"button.foreground": { "array": 1, "position": 1 },
			"button.hoverBackground": { "array": 0, "position": 1 },
			"button.secondaryForeground": { "array": 1, "position": 1 },
			"button.secondaryBackground": { "array": 1, "position": 8 },
			"button.secondaryHoverBackground": { "array": 1, "position": 9 },
			"input.background": { "array": 1, "position": 0 },
			"input.border": { "array": 1, "position": 1, "alpha": 0 },
			"input.foreground": { "array": 1, "position": 2 },
			"inputOption.activeBackground": { "array": 0, "position": 0, "alpha": 0.32 },
			"inputOption.activeBorder": { "array": 1, "position": 1, "alpha": 0 },
			"inputOption.activeForeground": { "array": 1, "position": 1 },
			"input.placeholderForeground": { "array": 1, "position": 5 },
			"textLink.foreground": { "array": 0, "position": 0 },
			"textLink.activeForeground": { "array": 0, "position": 1 },
			"editor.background": { "array": 1, "position": 0 },
			"editor.foreground": { "array": 1, "position": 2 },
			"editorLineNumber.foreground": { "array": 1, "position": 2 },
			"editorCursor.foreground": { "array": 0, "position": 0 },
			"editorCursor.background": { "array": 1, "position": 0 },
			"editor.selectionBackground": { "array": 0, "position": 0, "alpha": 0.25 },
			"editor.inactiveSelectionBackground": { "array": 0, "position": 4, "alpha": 0.13 },
			"editorWhitespace.foreground": { "array": 1, "position": 1, "alpha": 0 },
			"editor.selectionHighlightBackground": { "array": 0, "position": 4, "alpha": 0.13 },
			"editor.selectionHighlightBorder": { "array": 0, "position": 4 },
			"editor.findMatchBackground": { "array": 0, "position": 4, "alpha": 0.13 },
			"editor.findMatchBorder": { "array": 1, "position": 1, "alpha": 0 },
			"editor.findMatchHighlightBackground": { "array": 0, "position": 4, "alpha": 0.13 },
			"editor.findMatchHighlightBorder": { "array": 1, "position": 1, "alpha": 0 },
			"editor.findRangeHighlightBackground": "#3a3d4166",
			"editor.findRangeHighlightBorder": { "array": 1, "position": 1, "alpha": 0 },
			"editor.rangeHighlightBackground": { "array": 1, "position": 1, "alpha": 0.04 },
			"editor.rangeHighlightBorder": { "array": 1, "position": 1, "alpha": 0 },
			"editor.hoverHighlightBackground": { "array": 0, "position": 0, "alpha": 0.25 },
			"editor.wordHighlightStrongBackground": { "array": 0, "position": 0, "alpha": 0.25 },
			"editor.wordHighlightBackground": { "array": 1, "position": 9, "alpha": 0.22 },
			"editor.lineHighlightBackground": { "array": 1, "position": 1, "alpha": 0.04 },
			"editor.lineHighlightBorder": { "array": 1, "position": 1, "alpha": 0 },
			"editorLineNumber.activeForeground": { "array": 1, "position": 1 },
			"editorLink.activeForeground": { "array": 0, "position": 0 },
			"editorIndentGuide.background1": { "array": 1, "position": 1, "alpha": 0.05 },
			"editorIndentGuide.activeBackground1": { "array": 1, "position": 1, "alpha": 0.20 },
			"editorRuler.foreground": { "array": 1, "position": 1, "alpha": 0.10 },
			"editorBracketMatch.background": { "array": 0, "position": 0, "alpha": 0.1 },
			"editorBracketMatch.border": { "array": 1, "position": 6 },
			"editor.foldBackground": { "array": 0, "position": 0, "alpha": 0.14 },
			"editorOverviewRuler.background": { "array": 1, "position": 1, "alpha": 0 },
			"editorOverviewRuler.border": { "array": 1, "position": 1, "alpha": 0 },
			"editorError.foreground": "#f48771",
			"editorError.background": { "array": 1, "position": 1, "alpha": 0 },
			"editorError.border": { "array": 1, "position": 1, "alpha": 0 },
			"editorWarning.foreground": "#cca700",
			"editorWarning.background": { "array": 1, "position": 1, "alpha": 0 },
			"editorWarning.border": { "array": 1, "position": 1, "alpha": 0 },
			"editorInfo.foreground": "#75beff",
			"editorInfo.background": { "array": 1, "position": 1, "alpha": 0 },
			"editorInfo.border": { "array": 1, "position": 1, "alpha": 0 },
			"editorGutter.background": { "array": 1, "position": 0 },
			"editorGutter.modifiedBackground": "#01baee",
			"editorGutter.addedBackground": "#93d900",
			"editorGutter.deletedBackground": "#d70a14",
			"editorGutter.foldingControlForeground": "#c5c5c5",
			"editorCodeLens.foreground": "#99999997",
			"editorGroup.border": { "array": 1, "position": 1, "alpha": 0.05 },
			"editorGroup.dropBackground": { "array": 0, "position": 0, "alpha": 0.1 },
			"diffEditor.insertedTextBackground": "#b3ff0020",
			"diffEditor.removedTextBackground": "#ff000028",
			"diffEditor.border": "#444444",
			"panel.background": { "array": 1, "position": 0 },
			"panel.border": { "array": 1, "position": 1, "alpha": 0.05 },
			"panelTitle.activeBorder": { "array": 0, "position": 0 },
			"panelTitle.activeForeground": { "array": 1, "position": 1 },
			"panelTitle.inactiveForeground": { "array": 1, "position": 5 },
			"badge.background": { "array": 0, "position": 0 },
			"badge.foreground": { "array": 1, "position": 1 },
			"terminal.foreground": { "array": 1, "position": 4 },
			"terminal.selectionBackground": { "array": 1, "position": 1, "alpha": 0.09 },
			"terminalCursor.background": { "array": 0, "position": 0 },
			"terminalCursor.foreground": { "array": 1, "position": 1 },
			"terminal.border": { "array": 0, "position": 0, "alpha": 0.25 },
			"terminal.ansiBlack": { "array": 1, "position": 1 },
			"terminal.ansiBlue": "#2472c8",
			"terminal.ansiBrightBlack": "#666666",
			"terminal.ansiBrightBlue": "#3b8eea",
			"terminal.ansiBrightCyan": "#29b8db",
			"terminal.ansiBrightGreen": "#23d18b",
			"terminal.ansiBrightMagenta": "#d670d6",
			"terminal.ansiBrightRed": "#f14c4c",
			"terminal.ansiBrightWhite": "#e5e5e5",
			"terminal.ansiBrightYellow": "#f5f543",
			"terminal.ansiCyan": "#11a8cd",
			"terminal.ansiGreen": "#0dbc79",
			"terminal.ansiMagenta": "#bc3fbc",
			"terminal.ansiRed": "#cd3131",
			"terminal.ansiWhite": "#e5e5e5",
			"terminal.ansiYellow": "#e5e510",
			"breadcrumb.background": { "array": 1, "position": 0 },
			"breadcrumb.foreground": { "array": 1, "position": 4 },
			"breadcrumb.focusForeground": { "array": 0, "position": 0 },
			"editorGroupHeader.tabsBackground": { "array": 1, "position": 0 },
			"tab.activeForeground": { "array": 1, "position": 1 },
			"tab.border": { "array": 1, "position": 1, "alpha": 0 },
			"tab.activeBackground": { "array": 1, "position": 0 },
			"tab.activeBorder": { "array": 1, "position": 1, "alpha": 0 },
			"tab.activeBorderTop": { "array": 1, "position": 1, "alpha": 0 },
			"tab.inactiveBackground": { "array": 1, "position": 0 },
			"tab.inactiveForeground": { "array": 1, "position": 1, "alpha": 0.5 },
			"scrollbarSlider.background": { "array": 0, "position": 0, "alpha": 0.4 },
			"scrollbarSlider.hoverBackground": { "array": 0, "position": 0, "alpha": 0.7 },
			"scrollbarSlider.activeBackground": { "array": 0, "position": 0, "alpha": 0.4 },
			"progressBar.background": { "array": 0, "position": 0 },
			"widget.shadow": "#0000005c",
			"editorWidget.foreground": { "array": 1, "position": 4 },
			"editorWidget.background": { "array": 1, "position": 0 },
			"editorWidget.resizeBorder": { "array": 0, "position": 0 },
			"pickerGroup.border": { "array": 1, "position": 1, "alpha": 0 },
			"pickerGroup.foreground": { "array": 0, "position": 0 },
			"debugToolBar.background": { "array": 1, "position": 0 },
			"debugToolBar.border": { "array": 0, "position": 0, "alpha": 0.62 },
			"notifications.foreground": { "array": 1, "position": 4 },
			"notifications.background": { "array": 1, "position": 0 },
			"notificationToast.border": "#4747473a",
			"notificationsErrorIcon.foreground": "#f48771",
			"notificationsWarningIcon.foreground": "#cca700",
			"notificationsInfoIcon.foreground": "#75beff",
			"notificationCenter.border": "#47474752",
			"notificationCenterHeader.foreground": { "array": 1, "position": 1 },
			"notificationCenterHeader.background": { "array": 0, "position": 0 },
			"notifications.border": { "array": 1, "position": 1, "alpha": 0 },
			"gitDecoration.addedResourceForeground": "#90eca1",
			"gitDecoration.conflictingResourceForeground": "#3ea4ff",
			"gitDecoration.deletedResourceForeground": "#e24c32",
			"gitDecoration.ignoredResourceForeground": "#8c8c8c8f",
			"gitDecoration.modifiedResourceForeground": "#ffa067",
			"gitDecoration.stageDeletedResourceForeground": "#e24c32",
			"gitDecoration.stageModifiedResourceForeground": "#ffa067",
			"gitDecoration.submoduleResourceForeground": "#3efff6",
			"gitDecoration.untrackedResourceForeground": "#90eca1",
			"editorMarkerNavigation.background": { "array": 1, "position": 0 },
			"editorMarkerNavigationError.background": "#f48771",
			"editorMarkerNavigationWarning.background": "#cca700",
			"editorMarkerNavigationInfo.background": "#75beff",
			"merge.currentHeaderBackground": "#367366",
			"merge.currentContentBackground": "#27403B",
			"merge.incomingHeaderBackground": "#395F8F",
			"merge.incomingContentBackground": "#28384B",
			"merge.commonHeaderBackground": { "array": 1, "position": 8 },
			"merge.commonContentBackground": { "array": 1, "position": 9 },
			"editorSuggestWidget.background": { "array": 1, "position": 0 },
			"editorSuggestWidget.border": { "array": 1, "position": 1, "alpha": 0 },
			"editorSuggestWidget.foreground": { "array": 1, "position": 4 },
			"editorSuggestWidget.highlightForeground": { "array": 0, "position": 0 },
			"editorSuggestWidget.selectedBackground": { "array": 0, "position": 0, "alpha": 0.17 },
			"editorHoverWidget.foreground": { "array": 1, "position": 4 },
			"editorHoverWidget.background": { "array": 1, "position": 0 },
			"editorHoverWidget.border": { "array": 1, "position": 1, "alpha": 0.1 },
			"peekView.border": { "array": 0, "position": 0 },
			"peekViewEditor.background": { "array": 1, "position": 0 },
			"peekViewEditorGutter.background": { "array": 1, "position": 0 },
			"peekViewEditor.matchHighlightBackground": "#ff8f0099",
			"peekViewEditor.matchHighlightBorder": "#ee931e",
			"peekViewResult.background": { "array": 1, "position": 0 },
			"peekViewResult.fileForeground": { "array": 1, "position": 1 },
			"peekViewResult.lineForeground": { "array": 1, "position": 6 },
			"peekViewResult.matchHighlightBackground": "#ea5c004d",
			"peekViewResult.selectionBackground": { "array": 0, "position": 0, "alpha": 0.2 },
			"peekViewResult.selectionForeground": { "array": 1, "position": 1 },
			"peekViewTitle.background": { "array": 1, "position": 0 },
			"peekViewTitleDescription.foreground": { "array": 1, "position": 8, "alpha": 0.70 },
			"peekViewTitleLabel.foreground": { "array": 1, "position": 1 },
			"icon.foreground": { "array": 1, "position": 1 },
			"checkbox.background": { "array": 1, "position": 0 },
			"checkbox.foreground": { "array": 1, "position": 4 },
			"checkbox.border": { "array": 1, "position": 1, "alpha": 0 },
			"dropdown.background": { "array": 1, "position": 0 },
			"dropdown.foreground": { "array": 1, "position": 4 },
			"dropdown.border": { "array": 1, "position": 1, "alpha": 0 },
			"minimapGutter.addedBackground": "#93d900",
			"minimapGutter.modifiedBackground": "#01baee",
			"minimapGutter.deletedBackground": "#d70a14",
			"minimap.findMatchHighlight": { "array": 1, "position": 7 },
			"minimap.selectionHighlight": { "array": 0, "position": 0, "alpha": 0.25 },
			"minimap.errorHighlight": "#f48771",
			"minimap.warningHighlight": "#cca700",
			"minimap.background": { "array": 1, "position": 0 },
			"sideBar.dropBackground": "#79797918",
			"editorGroup.emptyBackground": { "array": 1, "position": 0 },
			"panelSection.border": { "array": 0, "position": 0, "alpha": 0.25 },
			"statusBarItem.activeBackground": { "array": 1, "position": 1, "alpha": 0.15 },
			"settings.headerForeground": { "array": 1, "position": 1 },
			"settings.focusedRowBackground": "#ffffff07",
			"walkThrough.embeddedEditorBackground": { "array": 1, "position": 0, "alpha": 0.31 },
			"breadcrumb.activeSelectionForeground": { "array": 1, "position": 3 },
			"editorGutter.commentRangeForeground": { "array": 1, "position": 4 },
			"debugExceptionWidget.background": { "array": 1, "position": 0 },
			"debugExceptionWidget.border": { "array": 0, "position": 0, "alpha": 0.62 }
		}
	}
}

export default colors